'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const repo=path.resolve(__dirname,'../../../../../..');
const p=require(path.join(repo,'src/zoho-catalyst/revenue-desk-analytics/tools/storage-qualification-preparer'));
const at=1800000000000,old=at-86400000,rev='a'.repeat(40),hash='b'.repeat(64);
function fixture(){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'sylvara-two-stage-synthetic-'));
 const save=(name,obj)=>{const f=path.join(root,name);fs.writeFileSync(f,JSON.stringify(obj));return f;};
 const projection=require(path.join(repo,'src/zoho-catalyst/revenue-desk-analytics/functions/analytics_sync/lib/report-run-store')).reportRunProjection;
 const fields={reportRuns:[...Object.keys(projection({kind:'report_attempt_v1',identity:{clientId:'synthetic',deploymentId:'synthetic',periodStart:'1970-01-01',periodEnd:'1970-01-01'}})),'IdempotencyKey','ReportRunId','ReportPayloadJson','RD_REPORT_VERSION'].sort(),eventReceipts:['EVENT_KEY','RECEIPT_KIND','STATUS','EVENT_TYPE','EVENT_DATA_JSON','PAYLOAD_FINGERPRINT','RECEIPT_VERSION','ATTEMPT_COUNT','SOURCE_REVISION','SOURCE_ENVIRONMENT','RECEIVED_AT','PROCESSED_AT'].sort()};
 const pins={organization:'606',projectId:'101000001',controllerFunctionId:'101000002',sourceRevision:rev,archiveSha256:hash,fileCount:308,deploymentId:'controller_'+rev,projections:fields};save('reviewed-pins.json',pins);
 const tables={reportRuns:{id:'101000003',name:'ReportRuns',schemaSha256:null,uniquenessSha256:null,uniqueField:'IdempotencyKey',projectionSha256:p.sha({projection:fields.reportRuns})},eventReceipts:{id:'101000004',name:'RevenueDeskEventReceipts',schemaSha256:null,uniquenessSha256:null,uniqueField:'EVENT_KEY',projectionSha256:p.sha({projection:fields.eventReceipts})}};
 save('binding.template.json',{schemaVersion:3,enabled:false,environment:'development',sourceRevision:rev,projectId:pins.projectId,controlHost:'synthetic.development.catalystserverless.com',tableId:tables.reportRuns.id,nonce:'<FRESH_32_HEX_NONCE_ONLY_WHEN_READY>',capability:{region:'US',origin:'https://api.catalyst.zoho.com',controllerFunctionId:pins.controllerFunctionId,deploymentId:pins.deploymentId,sdkVersion:'3.4.0',authMode:'user',authType:'admin',creatorPolicy:'observed_consistent_v1',tables,evidence:{}},verifiedAt:null,expiresAt:null,timeoutMs:3000,singleAdmittedInvocation:true});
 fs.writeFileSync(path.join(root,'caller.template.ds'),'synthetic __OPERATION_DIGEST__ __VERIFIED_AT__ __EXPIRES_AT__');
 const records={metadata:{organization:pins.organization,project:pins.projectId,environment:'Development',observedAt:new Date(old).toISOString(),metadata:[]},mapping:{observedAt:new Date(old).toISOString(),project:{id:pins.projectId},tables:Object.values(tables).map(x=>({id:x.id,name:x.name,projectId:pins.projectId}))},installation:{sourceRevision:rev,controllerFunctionId:pins.controllerFunctionId,archiveSha256:hash,fileCount:308,allFilesMatch:true,independentReadback:true,verifiedAt:old},controls:{observedAt:new Date(old).toISOString(),organization:pins.organization,projectId:pins.projectId,environment:'Development',controllerFunctionId:pins.controllerFunctionId,sourceRevision:rev,retellRouteMode:'disabled',deploymentMode:'active',storagePartKeys:[],controllerPinMatches:true,deploymentPinMatches:true,runtimeInvoked:false,bindings:Object.fromEntries(['runtime','storage','context','sender'].map(x=>[x,{jsonPresent:false,pinPresent:false,enabled:false}]))},sizing:{observedAt:new Date(old).toISOString(),baseline:{serializedBytes:2205,entryCount:36,controlledEntries:[]}},ownerAuthorization:{digest:hash,verifiedAt:old}};
 for(const [role,count]of [['reportRuns',33],['eventReceipts',29]]){
  const descriptor=tables[role],columns=require('./helpers/report-storage-schema-fixture').columns(role);
  assert.equal(columns.length,count);
  for(const [op,data]of [['list_all_columns',columns],['get_table_permissions',[{role_name:'App Administrator',role_id:'100',permissions:['SELECT','INSERT']},{role_name:'App User',role_id:'101',permissions:[]}]],['get_table_scopes',[{role_id:'100',scope:'GLOBAL'},{role_id:'101',scope:role==='reportRuns'?'USER':'GLOBAL'}]]])records.metadata.metadata.push({name:descriptor.name,id:descriptor.id,op,data});
 }
 const paths={metadata:'metadataFile',mapping:'projectMappingFile',controls:'controlsFile',installation:'installationFile',sizing:'sizingFile'};
 const input={ownerAuthorization:records.ownerAuthorization};for(const [role,key]of Object.entries(paths))input[key]=save(role+'.json',records[role]);
 const review=p.review(input,{at,root});const staticReviewFile=save('static-review.json',review);
 function final(){const current=structuredClone(records),provenance={schemaVersion:1,observations:{}};
  for(const role of Object.keys(current)){const key=['installation','ownerAuthorization'].includes(role)?'verifiedAt':'observedAt';current[role][key]=key==='observedAt'?new Date(at-1).toISOString():at-1;provenance.observations[role]={method:'independent_current_read',reference:'synthetic-read:'+role,observedAt:at-1,recordSha256:p.digest(current[role])};}
  const result={staticReviewFile,ownerAuthorization:current.ownerAuthorization,expiresAt:at+720000,operatorReady:true,nonce:'c'.repeat(32),provenanceFile:save('provenance.json',provenance)};
  for(const [role,key]of Object.entries(paths))result[key]=save('current-'+role+'.json',current[role]);return {input:result,current,provenance};}
 return {root,records,input,review,final,save};
}
test('static review retains old observations and creates no nonce, expiry, binding or claim',()=>{const f=fixture();assert.equal(f.review.originals.metadata.observedAt,new Date(old).toISOString());assert.equal(f.review.executable,false);for(const key of ['nonce','expiresAt','binding','operationDigest'])assert.equal(Object.hasOwn(f.review,key),false);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);});
function absentDescriptors(f){Object.assign(f.records.controls,{controllerPinPresent:false,deploymentPinPresent:false,controllerPinMatches:false,deploymentPinMatches:false});f.input.controlsFile=f.save('absent-controls.json',f.records.controls);f.review=p.review(f.input,{at,root:f.root});f.save('static-review.json',f.review);return f;}
test('static review rejects an omitted mandatory attempt count even with a matching obsolete projection hash',()=>{
 const f=fixture(),pins=JSON.parse(fs.readFileSync(path.join(f.root,'reviewed-pins.json'))),binding=JSON.parse(fs.readFileSync(path.join(f.root,'binding.template.json')));
 pins.projections.eventReceipts=pins.projections.eventReceipts.filter(x=>x!=='ATTEMPT_COUNT');
 binding.capability.tables.eventReceipts.projectionSha256=p.sha({projection:pins.projections.eventReceipts});
 f.save('reviewed-pins.json',pins);f.save('binding.template.json',binding);
 assert.throws(()=>p.review(f.input,{root:f.root,at}),/HELD/);
 assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);
});
for(const role of ['eventReceipts','reportRuns'])test('static review rejects a newly mandatory unsubmitted '+role+' column',()=>{
 const f=fixture(),entry=f.records.metadata.metadata.find(x=>x.name===(role==='eventReceipts'?'RevenueDeskEventReceipts':'ReportRuns')&&x.op==='list_all_columns');
 entry.data.find(x=>x.column_name===(role==='eventReceipts'?'CALL_KEY':'RecipientSnapshotJson')).is_mandatory=true;
 f.input.metadataFile=f.save('new-mandatory.json',f.records.metadata);
 assert.throws(()=>p.review(f.input,{root:f.root,at}),/HELD/);
 assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);
});
for(const change of ['type','length','mandatory'])test('static review rejects incompatible attempt-count '+change+' metadata',()=>{
 const f=fixture(),column=f.records.metadata.metadata.find(x=>x.name==='RevenueDeskEventReceipts'&&x.op==='list_all_columns').data.find(x=>x.column_name==='ATTEMPT_COUNT');
 if(change==='type')column.data_type='varchar';if(change==='length')column.max_length=0;if(change==='mandatory')column.is_mandatory=false;
 f.input.metadataFile=f.save('bad-attempt-column.json',f.records.metadata);
 assert.throws(()=>p.review(f.input,{root:f.root,at}),/HELD/);
 assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);
});
for(const role of ['eventReceipts','reportRuns'])for(const value of ['true',null,undefined])test('static review holds unknown mandatory status for an omitted '+role+' column '+String(value),()=>{
 const f=fixture(),column=f.records.metadata.metadata.find(x=>x.name===(role==='eventReceipts'?'RevenueDeskEventReceipts':'ReportRuns')&&x.op==='list_all_columns').data.find(x=>x.column_name===(role==='eventReceipts'?'CALL_KEY':'RecipientSnapshotJson'));
 column.is_mandatory=value;f.input.metadataFile=f.save('unknown-mandatory.json',f.records.metadata);
 assert.throws(()=>p.review(f.input,{root:f.root,at}),/HELD/);
 assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);
});
test('explicitly absent descriptors permit static review only and preserve observed state',()=>{const f=absentDescriptors(fixture());assert.equal(f.review.originals.controls.controllerPinPresent,false);assert.equal(f.review.originals.controls.deploymentPinMatches,false);assert.equal(f.review.executable,false);const fresh=f.final();assert.throws(()=>p.prepare(fresh.input,{at,root:f.root}),/HELD/);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);});
test('missing, partial, malformed or mismatched descriptor evidence holds static review',()=>{for(const change of ['missing','partial','malformed','mismatch']){const f=absentDescriptors(fixture()),c=structuredClone(f.records.controls);if(change==='missing')delete c.controllerPinPresent;if(change==='partial')c.controllerPinPresent=true;if(change==='malformed')c.deploymentPinPresent='false';if(change==='mismatch'){c.controllerPinPresent=true;c.deploymentPinPresent=true;}f.input.controlsFile=f.save('bad-descriptors.json',c);assert.throws(()=>p.review(f.input,{at,root:f.root}),/HELD/);}});
test('static review rejects contradictory or malformed presence despite asserted matches',()=>{for(const key of ['controllerPinPresent','deploymentPinPresent'])for(const value of [false,'true',null]){const f=fixture(),c={...f.records.controls,[key]:value};f.input.controlsFile=f.save('contradictory-presence.json',c);assert.throws(()=>p.review(f.input,{at,root:f.root}),/HELD/);}});
test('descriptor configuration and sizing changes require a new review before fresh preparation',()=>{const f=absentDescriptors(fixture()),fresh=f.final();Object.assign(fresh.current.controls,{controllerPinPresent:true,deploymentPinPresent:true,controllerPinMatches:true,deploymentPinMatches:true});fresh.current.sizing.baseline.serializedBytes+=100;fresh.current.sizing.baseline.entryCount+=2;for(const [role,key]of [['controls','controlsFile'],['sizing','sizingFile']]){fresh.input[key]=f.save('configured-'+role+'.json',fresh.current[role]);fresh.provenance.observations[role].recordSha256=p.digest(fresh.current[role]);}fresh.input.provenanceFile=f.save('configured-provenance.json',fresh.provenance);assert.throws(()=>p.prepare(fresh.input,{at,root:f.root}),/HELD/);const reviewedInput={...f.input,controlsFile:fresh.input.controlsFile,sizingFile:fresh.input.sizingFile};Object.assign(f.records.controls,fresh.current.controls);Object.assign(f.records.sizing,fresh.current.sizing);f.review=p.review(reviewedInput,{at,root:f.root});f.save('static-review.json',f.review);const ready=f.final();retimeAll(f,ready,at);assert.equal(p.prepare(ready.input,{at,root:f.root}).binding.capability.deploymentId,'controller_'+rev);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);});
test('final actual new comparisons preserve originals and same finite budget',()=>{const f=fixture(),fresh=f.final(),r=p.prepare(fresh.input,{at,root:f.root});assert.equal(r.reattestation.originals.installation.verifiedAt,old);assert.equal(r.binding.verifiedAt,at);assert.equal(r.manifest.maximumDataStoreAttempts,13);assert.equal(r.manifest.maximumRetainedSyntheticRows,3);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);});
test('final rejects stale or reused observations without renewing evidence',()=>{for(const time of [old,at-900001,at+1]){const f=fixture(),fresh=f.final();fresh.current.installation.verifiedAt=time;fresh.input.installationFile=f.save('bad-install.json',fresh.current.installation);fresh.provenance.observations.installation.observedAt=time;fresh.provenance.observations.installation.recordSha256=p.digest(fresh.current.installation);fresh.input.provenanceFile=f.save('bad-provenance.json',fresh.provenance);assert.throws(()=>p.prepare(fresh.input,{at,root:f.root}),/HELD/);}});
test('changed source, schema, controls, sizing or tenant holds despite matching new record provenance',()=>{for(const role of ['installation','metadata','controls','sizing','mapping']){const f=fixture(),fresh=f.final();if(role==='installation')fresh.current[role].sourceRevision='d'.repeat(40);if(role==='metadata')fresh.current[role].metadata[0].data[0].data_type='integer';if(role==='controls')fresh.current[role].retellRouteMode='isolated_test';if(role==='sizing')fresh.current[role].baseline.serializedBytes++;if(role==='mapping')fresh.current[role].project.id='999';const key={installation:'installationFile',metadata:'metadataFile',controls:'controlsFile',sizing:'sizingFile',mapping:'projectMappingFile'}[role];fresh.input[key]=f.save('changed.json',fresh.current[role]);fresh.provenance.observations[role].recordSha256=p.digest(fresh.current[role]);fresh.input.provenanceFile=f.save('changed-provenance.json',fresh.provenance);assert.throws(()=>p.prepare(fresh.input,{at,root:f.root}),/HELD/);}});
test('missing or tampered provenance, originals and template bytes hold',()=>{for(const change of ['missing','tampered','original','template']){const f=fixture(),fresh=f.final();if(change==='missing')delete fresh.provenance.observations.controls;if(change==='tampered')fresh.provenance.observations.metadata.recordSha256='0'.repeat(64);if(change==='original'){f.review.originals.controls.runtimeInvoked=true;fresh.input.staticReviewFile=f.save('tampered-review.json',f.review);}if(change==='template')fs.appendFileSync(path.join(f.root,'caller.template.ds'),' changed');fresh.input.provenanceFile=f.save('bad-provenance.json',fresh.provenance);assert.throws(()=>p.prepare(fresh.input,{at,root:f.root}),/HELD/);}});
test('synthetic UTF8 text envelope rejects whitespace, unicode and hash changes',()=>{const text='{"kind":"synthetic","text":"Inter â€” cafÃ© ðŸ‘·","n":13}\r\n',e={schemaVersion:1,kind:'synthetic_transport_probe_v1',text,utf8Bytes:Buffer.byteLength(text),sha256:p.sha(text)};assert.equal(p.verifyObservationText(JSON.parse(JSON.stringify(e))).sha256,e.sha256);for(const changed of [text.trim(),text.replace('cafÃ©','cafe'),text.replace('\r\n','\n')])assert.throws(()=>p.verifyObservationText({...e,text:changed}),/HELD/);});

test('static output cannot consume a final claim; final writer refuses a repeat',()=>{const f=fixture();assert.throws(()=>p.write(f.review,path.join(f.root,'denied'),{root:f.root}),/HELD/);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);const fresh=f.final(),result=p.prepare(fresh.input,{at,root:f.root});p.write(result,path.join(f.root,'synthetic-prepared'),{root:f.root,at});assert.equal(fs.existsSync(path.join(f.root,'synthetic-prepared/reattestation-private.json')),true);assert.throws(()=>p.write(result,path.join(f.root,'repeat'),{root:f.root,at}),/EEXIST/);});

function witnessInput(f){const fresh=f.final(),witnesses={};for(const role of Object.keys(fresh.current)){const record=fresh.current[role],key=['installation','ownerAuthorization'].includes(role)?'verifiedAt':'observedAt';const state=structuredClone(record);delete state[key];witnesses[role]={role,...fresh.provenance.observations[role],stateSha256:p.digest(state)};}const envelope={schemaVersion:1,kind:'current_read_witnesses_v1',staticReviewSha256:p.sha(fs.readFileSync(fresh.input.staticReviewFile,'utf8')),witnesses};envelope.sha256=p.digest(envelope);return {envelope,input:{staticReviewFile:fresh.input.staticReviewFile,witnessFile:f.save('witnesses.json',envelope),expiresAt:fresh.input.expiresAt,operatorReady:true,stagingDirectory:path.join(f.root,'derived')}};}
test('compact witnessed records preserve originals and explicit derivation',()=>{const f=fixture(),w=witnessInput(f),r=p.prepareWitnesses(w.input,{root:f.root,at});assert.equal(r.reattestation.evidenceForm,'derived_original_plus_current_read_witness_v1');assert.equal(r.reattestation.originals.installation.verifiedAt,old);assert.deepEqual(r.reattestation.witnessEnvelope,w.envelope);});
test('all six freshness horizons and proposed expiry need ten minutes before claim',()=>{for(const role of Object.keys(fixture().records)){const f=fixture(),fresh=f.final(),key=['installation','ownerAuthorization'].includes(role)?'verifiedAt':'observedAt';fresh.current[role][key]=key==='observedAt'?new Date(at-300001).toISOString():at-300001;fresh.provenance.observations[role].observedAt=at-300001;fresh.provenance.observations[role].recordSha256=p.digest(fresh.current[role]);fresh.input.provenanceFile=f.save('late-provenance.json',fresh.provenance);if(role==='ownerAuthorization')fresh.input.ownerAuthorization=fresh.current[role];else fresh.input[{metadata:'metadataFile',mapping:'projectMappingFile',controls:'controlsFile',installation:'installationFile',sizing:'sizingFile'}[role]]=f.save('late-record.json',fresh.current[role]);assert.throws(()=>p.prepare(fresh.input,{root:f.root,at}),/HELD/);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);}const f=fixture(),fresh=f.final();fresh.input.expiresAt=at+599999;assert.throws(()=>p.prepare(fresh.input,{root:f.root,at}),/HELD/);});
test('writer rechecks window immediately before immutable claim',()=>{const f=fixture(),fresh=f.final(),r=p.prepare(fresh.input,{root:f.root,at});assert.throws(()=>p.write(r,path.join(f.root,'late'),{root:f.root,at:at+120001}),/HELD/);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);});
test('compact witness tampering, swapped role and changed state hold before nonce staging',()=>{for(const change of ['state','record','reference','timestamp','role','replay','envelope']){const f=fixture(),w=witnessInput(f),v=w.envelope.witnesses.metadata;if(change==='state')v.stateSha256='0'.repeat(64);if(change==='record')v.recordSha256='0'.repeat(64);if(change==='reference')v.reference='secret-bearing/url';if(change==='timestamp')v.observedAt--;if(change==='role')v.role='controls';if(change==='replay')v.observedAt=old;if(change==='envelope')v.reference='another-valid-reference';else{delete w.envelope.sha256;w.envelope.sha256=p.digest(w.envelope);}w.input.witnessFile=f.save('bad-witness.json',w.envelope);assert.throws(()=>p.prepareWitnesses(w.input,{root:f.root,at}),/HELD/);assert.equal(fs.existsSync(w.input.stagingDirectory),false);}});
test('packaging preflight failure and missing upload discovery create neither staging nor claim',()=>{const runner=require(path.join(repo,'src/zoho-catalyst/revenue-desk-analytics/tools/storage-qualification-local-runner'));for(const failure of ['packaging','upload']){const f=fixture(),w=witnessInput(f);assert.throws(()=>runner.run({...w.input,destination:path.join(f.root,'out'),archive:path.join(f.root,'out.zip')},{root:f.root,at,python:'synthetic-python',uploadToolAvailable:failure!=='upload',packagingPreflight:()=>{throw Error('packaging unavailable');}}));assert.equal(fs.existsSync(w.input.stagingDirectory),false);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);}});

test('automated runner packages one claim and refuses repeated finalization',()=>{const runner=require(path.join(repo,'src/zoho-catalyst/revenue-desk-analytics/tools/storage-qualification-local-runner')),f=fixture(),w=witnessInput(f);fs.copyFileSync(path.join(repo,'src/zoho-catalyst/revenue-desk-analytics/functions/analytics_sync/lib/report-storage-binding.js'),path.join(f.root,'report-storage-binding.js'));let probes=0,packages=0;const input={...w.input,destination:path.join(f.root,'out'),archive:path.join(f.root,'out.zip')};const options={root:f.root,at,python:'synthetic-python',uploadToolAvailable:true,packagingPreflight:()=>{probes++;},packageOutput:(_python,_dir,archive)=>{packages++;fs.writeFileSync(archive,'synthetic archive');}};const receipt=runner.run(input,options);assert.equal(probes,1);assert.equal(packages,1);assert.equal(receipt.providerRequests,0);assert.equal(receipt.archiveSha256,require('node:crypto').createHash('sha256').update('synthetic archive').digest('hex'));assert.throws(()=>runner.run(input,options),/HELD/);assert.equal(packages,1);});
test('post-claim packaging failure retains claim and never silently repeats',()=>{const runner=require(path.join(repo,'src/zoho-catalyst/revenue-desk-analytics/tools/storage-qualification-local-runner')),f=fixture(),w=witnessInput(f);const input={...w.input,destination:path.join(f.root,'out'),archive:path.join(f.root,'out.zip')},options={root:f.root,at,python:'synthetic-python',uploadToolAvailable:true,packagingPreflight:()=>{},packageOutput:()=>{throw Error('local disk failure');}};assert.throws(()=>runner.run(input,options),/local disk failure/);const claim=fs.readFileSync(path.join(f.root,'PREPARATION-CLAIM.json'),'utf8');assert.throws(()=>runner.run(input,options),/HELD/);assert.equal(fs.readFileSync(path.join(f.root,'PREPARATION-CLAIM.json'),'utf8'),claim);});

function schema4Fixture(){const f=fixture(),b=JSON.parse(fs.readFileSync(path.join(f.root,'binding.template.json'),'utf8'));b.schemaVersion=4;fs.writeFileSync(path.join(f.root,'binding.template.json'),JSON.stringify(b));f.review=p.review(f.input,{root:f.root,at});const fresh=f.final();fresh.input.staticReviewFile=f.save('schema4-static.json',f.review);return {f,fresh};}
test('schema5 preparer binds sequential operation identity and seven-attempt manifest without live claim',()=>{
 const {f,fresh}=schema4Fixture(),b=JSON.parse(fs.readFileSync(path.join(f.root,'binding.template.json'),'utf8'));
 b.schemaVersion=5;fs.writeFileSync(path.join(f.root,'binding.template.json'),JSON.stringify(b));
 const reviewed=p.review(f.input,{root:f.root,at});
 assert.equal(reviewed.maximumDataStoreAttempts,7);assert.equal(reviewed.mechanism,'sequential_unique_diagnostic_v1');assert.equal(reviewed.concurrencyProven,false);
 fresh.input.staticReviewFile=f.save('schema5-static.json',reviewed);
 retimeAll(f,fresh,at);fresh.input.expiresAt=at+899999;
 const r=p.prepare(fresh.input,{root:f.root,at});assert.equal(r.binding.schemaVersion,5);assert.equal(r.manifest.maximumDataStoreAttempts,7);
 assert.equal(r.manifest.mechanism,'sequential_unique_diagnostic_v1');assert.equal(r.manifest.concurrencyProven,false);assert.equal(Object.hasOwn(r.manifest.keys,'successor'),false);
 for(const change of ['budget','mechanism','authority','missing']){const bad=structuredClone(reviewed);if(change==='budget')bad.maximumDataStoreAttempts=13;if(change==='mechanism')bad.mechanism='unique_insert_successor_v1';if(change==='authority')bad.concurrencyProven=true;if(change==='missing')delete bad.concurrencyProven;fresh.input.staticReviewFile=f.save('tampered-schema5-'+change+'.json',bad);assert.throws(()=>p.prepare(fresh.input,{root:f.root,at}),/HELD/);}
 const {canonicalJson}=require('../lib/facts'),crypto=require('node:crypto');
 const expected=crypto.createHash('sha256').update(canonicalJson({mechanism:'sequential_unique_diagnostic_v1',projectId:r.binding.projectId,tables:r.binding.capability.tables,nonce:r.binding.nonce,sourceRevision:r.binding.sourceRevision,capabilitySha256:p.sha(r.binding.capability)})).digest('hex');
 assert.equal(r.operationDigest,expected);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);
});
function retimeAll(f,fresh,time){for(const role of Object.keys(fresh.current)){const key=['installation','ownerAuthorization'].includes(role)?'verifiedAt':'observedAt';fresh.current[role][key]=key==='observedAt'?new Date(time).toISOString():time;fresh.provenance.observations[role].observedAt=time;fresh.provenance.observations[role].recordSha256=p.digest(fresh.current[role]);if(role==='ownerAuthorization')fresh.input.ownerAuthorization=fresh.current[role];else fresh.input[{metadata:'metadataFile',mapping:'projectMappingFile',controls:'controlsFile',installation:'installationFile',sizing:'sizingFile'}[role]]=f.save('retimed-'+role+'.json',fresh.current[role]);}fresh.input.provenanceFile=f.save('retimed-provenance.json',fresh.provenance);}
test('schema4 preparer accepts exactly60minutes within every genuine evidence horizon',()=>{const {f,fresh}=schema4Fixture();retimeAll(f,fresh,at);fresh.input.expiresAt=at+3600000;const r=p.prepare(fresh.input,{root:f.root,at});assert.equal(r.binding.schemaVersion,4);assert.equal(r.binding.expiresAt-r.binding.verifiedAt,3600000);assert.equal(r.manifest.maximumDataStoreAttempts,13);assert.equal(r.manifest.maximumRetainedSyntheticRows,3);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);fresh.input.expiresAt++;assert.throws(()=>p.prepare(fresh.input,{root:f.root,at}),/HELD/);});
test('schema4 accepts30minute-old genuine evidence without restamping; schema3 still holds',()=>{const {f,fresh}=schema4Fixture();retimeAll(f,fresh,at-1800000);const r=p.prepare(fresh.input,{root:f.root,at});assert.equal(r.reattestation.observations.installation.verifiedAt,at-1800000);const b=JSON.parse(fs.readFileSync(path.join(f.root,'binding.template.json'),'utf8'));b.schemaVersion=3;fs.writeFileSync(path.join(f.root,'binding.template.json'),JSON.stringify(b));fresh.input.staticReviewFile=f.save('legacy-review.json',p.review(f.input,{root:f.root,at}));assert.throws(()=>p.prepare(fresh.input,{root:f.root,at}),/HELD/);});
test('schema4 retains ten-minute margin and rechecks it before writing a claim',()=>{const {f,fresh}=schema4Fixture();fresh.input.expiresAt=at+3599999;const r=p.prepare(fresh.input,{root:f.root,at});assert.throws(()=>p.write(r,path.join(f.root,'late60'),{root:f.root,at:at+2999999+1}),/HELD/);assert.equal(fs.existsSync(path.join(f.root,'PREPARATION-CLAIM.json')),false);retimeAll(f,fresh,at-3000001);assert.throws(()=>p.prepare(fresh.input,{root:f.root,at}),/HELD/);});
test('unknown or production diagnostic template cannot select extended preparation',()=>{for(const change of ['schema','environment']){const f=fixture(),b=JSON.parse(fs.readFileSync(path.join(f.root,'binding.template.json'),'utf8'));if(change==='schema')b.schemaVersion=6;else{b.schemaVersion=4;b.environment='production';}fs.writeFileSync(path.join(f.root,'binding.template.json'),JSON.stringify(b));assert.throws(()=>p.review(f.input,{root:f.root,at}),/HELD/);}});
