"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const functionRoot = path.resolve(__dirname, "..");
const controllerRoot = path.resolve(functionRoot, "../..");
const repositoryRoot = path.resolve(controllerRoot, "../../..");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function sorted(values) {
  return [...values].sort();
}

function walkFiles(root, relativeDirectory = "") {
  const absoluteDirectory = path.join(root, relativeDirectory);
  const files = [];
  for (const entry of fs.readdirSync(absoluteDirectory, { withFileTypes: true })) {
    const relativePath = path.posix.join(
      relativeDirectory.split(path.sep).join(path.posix.sep),
      entry.name,
    );
    if (entry.isDirectory()) {
      files.push(...walkFiles(root, relativePath));
    } else if (entry.isFile()) {
      files.push(relativePath);
    }
  }
  return files;
}

function matchesManifestIgnore(relativePath, patterns) {
  const normalized = relativePath.split(path.sep).join(path.posix.sep);
  return patterns.some((pattern) => {
    if (pattern.endsWith("/**")) {
      const directory = pattern.slice(0, -3).replace(/\/$/, "");
      return normalized === directory || normalized.startsWith(`${directory}/`);
    }
    if (pattern.endsWith("*") && !pattern.slice(0, -1).includes("*")) {
      const prefix = pattern.slice(0, -1);
      return pattern.includes("/")
        ? normalized.startsWith(prefix)
        : path.posix.basename(normalized).startsWith(prefix);
    }
    return normalized === pattern;
  });
}

test("the public variable registry and placeholder environment file stay in lockstep", () => {
  const registryPath = path.resolve(functionRoot, "../../config/variables.json");
  const registry = readJson(registryPath);
  const names = registry.variables.map((entry) => entry.name);
  assert.equal(new Set(names).size, names.length);

  const exampleNames = fs.readFileSync(path.join(functionRoot, ".env.example"), "utf8")
    .split(/\r?\n/)
    .filter((line) => line && !line.startsWith("#"))
    .map((line) => line.slice(0, line.indexOf("=")));
  assert.deepEqual([...names].sort(), [...exampleNames].sort());

  const example = fs.readFileSync(path.join(functionRoot, ".env.example"), "utf8");
  assert.doesNotMatch(example, /Zoho-oauthtoken|client_secret|refresh_token|@/i);
  assert.equal(registry.variables.filter((entry) => entry.classification.includes("secret"))
    .every((entry) => entry.example_allowed === false), true);
});

test("the Data Store schema defines every durable key as mandatory and unique", () => {
  const schemaPath = path.join(controllerRoot, "config/datastore-schema.json");
  const schema = readJson(schemaPath);
  const { STORED_FIELDS } = require("../lib/session-store");
  const {
    PREFILL_STORED_FIELDS,
    SUBMISSION_STORED_FIELDS,
  } = require("../lib/workflow-store");
  const runtimeFields = new Map([
    ["SESSION_TABLE_NAME", STORED_FIELDS],
    ["PREFILL_TABLE_NAME", PREFILL_STORED_FIELDS],
    ["SUBMISSION_TABLE_NAME", SUBMISSION_STORED_FIELDS],
  ]);
  const expectedUniqueColumns = new Map([
    ["SESSION_TABLE_NAME", ["ISSUE_KEY", "TOKEN_HASH"]],
    ["PREFILL_TABLE_NAME", ["PREFILL_KEY"]],
    ["SUBMISSION_TABLE_NAME", ["SUBMISSION_KEY"]],
  ]);

  assert.equal(schema.tables.length, 3);
  assert.deepEqual(
    sorted(schema.tables.map((table) => table.runtime_variable)),
    sorted(runtimeFields.keys()),
  );

  for (const table of schema.tables) {
    const columns = new Map(table.columns.map((column) => [column.api_name, column]));
    assert.equal(columns.size, table.columns.length, `${table.runtime_variable} has duplicate columns`);
    assert.equal(columns.has("ROWID"), false, "ROWID is generated by Catalyst, not provisioned");

    const exportedFields = runtimeFields.get(table.runtime_variable);
    assert.ok(exportedFields, `unexpected runtime variable ${table.runtime_variable}`);
    assert.equal(exportedFields.filter((field) => field === "ROWID").length, 1);
    assert.deepEqual(
      sorted(exportedFields.filter((field) => field !== "ROWID")),
      sorted(columns.keys()),
      `${table.runtime_variable} runtime and provisioned fields differ`,
    );

    const expectedUnique = expectedUniqueColumns.get(table.runtime_variable);
    assert.deepEqual(sorted(table.required_unique_columns), sorted(expectedUnique));
    assert.deepEqual(
      sorted(table.columns.filter((column) => column.unique).map((column) => column.api_name)),
      sorted(expectedUnique),
      `${table.runtime_variable} has an undeclared or missing unique column`,
    );
    for (const key of table.required_unique_columns) {
      assert.equal(columns.get(key)?.mandatory, true);
      assert.equal(columns.get(key)?.unique, true);
    }
  }
  assert.equal(JSON.stringify(schema).includes("RAW_PAYLOAD"), false);
});

test("the Catalyst and npm manifests describe one consistent Advanced IO target", () => {
  const catalyst = readJson(path.join(controllerRoot, "catalyst.json"));
  assert.equal(catalyst.functions.source, "functions");
  assert.deepEqual(catalyst.functions.targets, ["form2_controller"]);
  assert.deepEqual(catalyst.functions.ignore, ["test/**", ".env*"]);

  const sourceRoot = path.join(controllerRoot, catalyst.functions.source);
  const targetRoot = path.join(sourceRoot, catalyst.functions.targets[0]);
  assert.equal(path.resolve(targetRoot), functionRoot);
  assert.equal(fs.statSync(sourceRoot).isDirectory(), true);
  assert.equal(fs.statSync(targetRoot).isDirectory(), true);

  const catalystConfigPath = path.join(targetRoot, "catalyst-config.json");
  const packagePath = path.join(targetRoot, "package.json");
  const packageLockPath = path.join(targetRoot, "package-lock.json");
  const catalystConfig = readJson(catalystConfigPath);
  const packageJson = readJson(packagePath);
  const packageLock = readJson(packageLockPath);

  assert.deepEqual(catalystConfig.deployment, {
    name: "form2_controller",
    stack: "node24",
    type: "advancedio",
  });
  assert.deepEqual(catalystConfig.execution, { main: "index.js" });
  assert.equal(catalystConfig.deployment.name, catalyst.functions.targets[0]);
  assert.equal(packageJson.main, catalystConfig.execution.main);
  assert.equal(packageJson.engines.node, "24.x");
  assert.equal(packageJson.dependencies["zcatalyst-sdk-node"], "3.4.0");

  assert.equal(packageLock.lockfileVersion, 3);
  assert.equal(packageLock.name, packageJson.name);
  assert.equal(packageLock.version, packageJson.version);
  assert.equal(packageLock.packages[""].name, packageJson.name);
  assert.equal(packageLock.packages[""].version, packageJson.version);
  assert.equal(packageLock.packages[""].engines.node, packageJson.engines.node);
  assert.equal(
    packageLock.packages[""].dependencies["zcatalyst-sdk-node"],
    packageJson.dependencies["zcatalyst-sdk-node"],
  );
  assert.equal(packageLock.packages["node_modules/zcatalyst-sdk-node"].version, "3.4.0");
  assert.match(
    packageLock.packages["node_modules/zcatalyst-sdk-node"].resolved,
    /\/zcatalyst-sdk-node-3\.4\.0\.tgz$/,
  );
  assert.match(
    packageLock.packages["node_modules/zcatalyst-sdk-node"].integrity,
    /^sha512-[A-Za-z0-9+/]+=*$/,
  );

  for (const referencedFile of [
    catalystConfig.execution.main,
    "catalyst-config.json",
    "package.json",
    "package-lock.json",
  ]) {
    assert.equal(
      fs.statSync(path.join(targetRoot, referencedFile)).isFile(),
      true,
      `${referencedFile} is missing`,
    );
  }

  const checkedSources = [...packageJson.scripts.check.matchAll(/\bnode --check ([\w./-]+\.js)/g)]
    .map((match) => match[1]);
  const runtimeSources = walkFiles(targetRoot)
    .filter((relativePath) => relativePath === "index.js" || /^lib\/.*\.js$/.test(relativePath));
  assert.deepEqual(sorted(checkedSources), sorted(runtimeSources));
  for (const sourceFile of checkedSources) {
    assert.equal(fs.statSync(path.join(targetRoot, sourceFile)).isFile(), true);
  }
});

test("the intended function archive excludes tests and environment files", () => {
  const catalyst = readJson(path.join(controllerRoot, "catalyst.json"));
  const targetRoot = path.join(
    controllerRoot,
    catalyst.functions.source,
    catalyst.functions.targets[0],
  );
  const allFiles = walkFiles(targetRoot);
  const archiveFiles = allFiles.filter(
    (relativePath) => !matchesManifestIgnore(relativePath, catalyst.functions.ignore),
  );

  assert.ok(allFiles.includes("test/registry.test.js"));
  assert.ok(allFiles.includes(".env.example"));
  assert.equal(archiveFiles.some((relativePath) => relativePath.startsWith("test/")), false);
  assert.equal(
    archiveFiles.some((relativePath) => path.posix.basename(relativePath).startsWith(".env")),
    false,
  );

  for (const requiredFile of [
    "index.js",
    "catalyst-config.json",
    "package.json",
    "package-lock.json",
  ]) {
    assert.ok(archiveFiles.includes(requiredFile), `${requiredFile} is absent from the archive`);
  }
  const runtimeLibraries = allFiles.filter((relativePath) => /^lib\/.*\.js$/.test(relativePath));
  assert.ok(runtimeLibraries.length > 0);
  for (const runtimeLibrary of runtimeLibraries) {
    assert.ok(archiveFiles.includes(runtimeLibrary), `${runtimeLibrary} is absent from the archive`);
  }
});

test("the repository pipeline gates and reproduces one immutable Development deploy", () => {
  const pipelinePath = path.join(repositoryRoot, "catalyst-pipelines.yaml");
  const scriptPath = path.join(controllerRoot, "scripts/deploy-development.sh");
  const pipeline = fs.readFileSync(pipelinePath, "utf8");
  const script = fs.readFileSync(scriptPath, "utf8");

  assert.match(pipeline, /^version: 1$/m);
  assert.match(pipeline, /^  approve:\n    type:\n      type-name: approval$/m);
  assert.ok(
    pipeline.indexOf("- name: approval") < pipeline.indexOf("- name: development"),
    "the approval stage must precede the deployment stage",
  );
  for (const variableName of [
    "DEPLOY_APPROVER_EMAIL",
    "PROJECT_ID",
    "CATALYST_ORG",
    "CATALYST_TOKEN",
    "APPROVED_SOURCE_REVISION",
  ]) {
    assert.match(pipeline, new RegExp(`<< env\\.${variableName} >>`));
  }
  assert.match(
    pipeline,
    /bash src\/zoho-catalyst\/form2-controller\/scripts\/deploy-development\.sh/,
  );

  assert.notEqual(fs.statSync(scriptPath).mode & 0o111, 0, "deployment script is not executable");
  assert.match(script, /^#!\/usr\/bin\/env bash\nset -euo pipefail$/m);
  assert.match(script, /readonly NODE_VERSION="24\.18\.0"/);
  assert.match(script, /readonly CATALYST_CLI_VERSION="1\.26\.1"/);
  assert.match(script, /readonly NODE_SHA256="[a-f0-9]{64}"/);
  assert.match(script, /actual_revision.*git .* rev-parse --verify HEAD/);
  assert.match(script, /actual_revision" == "\$APPROVED_SOURCE_REVISION/);
  assert.match(script, /status --porcelain=v1 --untracked-files=all/);
  assert.match(script, /archive --format=tar "\$actual_revision"/);
  assert.match(script, /functions\/form2_controller\/lib\/source-revision\.js/);
  assert.match(script, /ARTIFACT_SOURCE_REVISION/);
  assert.match(script, /artifact_project_root/);
  assert.match(script, /tools\/safety\/pre-commit-safety-check\.py/);
  assert.match(script, /npm ci --ignore-scripts --no-audit --no-fund/);
  assert.match(script, /npm run ci --prefix/);
  assert.doesNotMatch(script, /npm install[^\n]*zcatalyst-cli|zcatalyst-cli@/);
  assert.equal((script.match(/\bcatalyst deploy\b/g) ?? []).length, 1);
  assert.match(script, /--only functions:form2_controller/);
  assert.match(script, /--ignore-scripts/);
  assert.match(script, /--project "\$PROJECT_ID"/);
  assert.match(script, /--org "\$CATALYST_ORG"/);
  assert.match(script, /--token "\$CATALYST_TOKEN"/);
  assert.match(script, /--dc us/);
  assert.doesNotMatch(script, /set -x|--verbose/);
});
