"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const functionRoot = path.resolve(__dirname, "..");
const controllerRoot = path.resolve(functionRoot, "../..");
const repositoryRoot = path.resolve(controllerRoot, "../../..");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function sorted(values) {
  return [...values].sort();
}

function walkFiles(root, relativeDirectory = "") {
  const absoluteDirectory = path.join(root, relativeDirectory);
  const files = [];
  for (const entry of fs.readdirSync(absoluteDirectory, { withFileTypes: true })) {
    const relativePath = path.posix.join(
      relativeDirectory.split(path.sep).join(path.posix.sep),
      entry.name,
    );
    if (entry.isDirectory()) {
      files.push(...walkFiles(root, relativePath));
    } else if (entry.isFile()) {
      files.push(relativePath);
    }
  }
  return files;
}

function matchesManifestIgnore(relativePath, patterns) {
  const normalized = relativePath.split(path.sep).join(path.posix.sep);
  return patterns.some((pattern) => {
    if (pattern.endsWith("/**")) {
      const directory = pattern.slice(0, -3).replace(/\/$/, "");
      return normalized === directory || normalized.startsWith(`${directory}/`);
    }
    if (pattern.endsWith("*") && !pattern.slice(0, -1).includes("*")) {
      const prefix = pattern.slice(0, -1);
      return pattern.includes("/")
        ? normalized.startsWith(prefix)
        : path.posix.basename(normalized).startsWith(prefix);
    }
    return normalized === pattern;
  });
}

test("the public variable registry and placeholder environment file stay in lockstep", () => {
  const registryPath = path.resolve(functionRoot, "../../config/variables.json");
  const registry = readJson(registryPath);
  const names = registry.variables.map((entry) => entry.name);
  assert.equal(new Set(names).size, names.length);

  const exampleNames = fs.readFileSync(path.join(functionRoot, ".env.example"), "utf8")
    .split(/\r?\n/)
    .filter((line) => line && !line.startsWith("#"))
    .map((line) => line.slice(0, line.indexOf("=")));
  assert.deepEqual([...names].sort(), [...exampleNames].sort());

  const example = fs.readFileSync(path.join(functionRoot, ".env.example"), "utf8");
  assert.doesNotMatch(example, /Zoho-oauthtoken|client_secret|refresh_token|@/i);
  assert.equal(registry.variables.filter((entry) => entry.classification.includes("secret"))
    .every((entry) => entry.example_allowed === false), true);
});

test("the Data Store schema matches the runtime and Catalyst uniqueness boundary", () => {
  const schemaPath = path.join(controllerRoot, "config/datastore-schema.json");
  const schema = readJson(schemaPath);
  const { STORED_FIELDS } = require("../lib/session-store");
  const {
    PREFILL_STORED_FIELDS,
    SUBMISSION_STORED_FIELDS,
  } = require("../lib/workflow-store");
  const runtimeFields = new Map([
    ["SESSION_TABLE_NAME", STORED_FIELDS],
    ["PREFILL_TABLE_NAME", PREFILL_STORED_FIELDS],
    ["SUBMISSION_TABLE_NAME", SUBMISSION_STORED_FIELDS],
  ]);
  const expectedUniqueColumns = new Map([
    ["SESSION_TABLE_NAME", ["ISSUE_REQUEST_KEY", "DEAL_ISSUANCE_KEY"]],
    ["PREFILL_TABLE_NAME", ["PREFILL_KEY"]],
    ["SUBMISSION_TABLE_NAME", ["SUBMISSION_KEY"]],
  ]);

  assert.equal(schema.status, "proposed-development-only");
  assert.equal(
    schema.live_state,
    "retell-development-54-column-version-2-copy-verified-legacy-live-function-routes-variables-callers-not-cut-over-version-3-not-applied",
  );
  assert.equal(schema.observed_at, "2026-08-22");

  assert.equal(schema.tables.length, 3);
  assert.equal(
    schema.tables.reduce((total, table) => total + table.columns.length, 0),
    55,
  );
  assert.deepEqual(
    sorted(schema.tables.map((table) => table.runtime_variable)),
    sorted(runtimeFields.keys()),
  );

  for (const table of schema.tables) {
    const columns = new Map(table.columns.map((column) => [column.api_name, column]));
    assert.equal(columns.size, table.columns.length, `${table.runtime_variable} has duplicate columns`);
    assert.equal(columns.has("ROWID"), false, "ROWID is generated by Catalyst, not provisioned");

    const exportedFields = runtimeFields.get(table.runtime_variable);
    assert.ok(exportedFields, `unexpected runtime variable ${table.runtime_variable}`);
    assert.equal(exportedFields.filter((field) => field === "ROWID").length, 1);
    assert.deepEqual(
      sorted(exportedFields.filter((field) => field !== "ROWID")),
      sorted(columns.keys()),
      `${table.runtime_variable} runtime and provisioned fields differ`,
    );

    const expectedUnique = expectedUniqueColumns.get(table.runtime_variable);
    assert.deepEqual(sorted(table.required_unique_columns), sorted(expectedUnique));
    assert.deepEqual(
      sorted(table.columns.filter((column) => column.unique).map((column) => column.api_name)),
      sorted(expectedUnique),
      `${table.runtime_variable} has an undeclared or missing unique column`,
    );
    for (const key of table.required_unique_columns) {
      assert.equal(columns.get(key)?.mandatory, true);
      assert.equal(columns.get(key)?.unique, true);
    }
    assert.ok(
      table.columns.filter((column) => column.type === "varchar" && column.unique).length <= 2,
      `${table.runtime_variable} exceeds Catalyst's verified unique varchar limit`,
    );
  }
  const sessionTable = schema.tables.find(
    (table) => table.runtime_variable === "SESSION_TABLE_NAME",
  );
  const sessionColumns = new Map(
    sessionTable.columns.map((column) => [column.api_name, column]),
  );
  assert.deepEqual(sessionColumns.get("DEAL_ISSUANCE_KEY"), {
    api_name: "DEAL_ISSUANCE_KEY",
    type: "varchar",
    max_length: 64,
    mandatory: true,
    unique: true,
    pii_ephi: true,
  });
  assert.deepEqual(sessionColumns.get("ISSUE_REQUEST_KEY"), {
    api_name: "ISSUE_REQUEST_KEY",
    type: "varchar",
    max_length: 64,
    mandatory: true,
    unique: true,
    pii_ephi: true,
  });
  assert.deepEqual(sessionColumns.get("ACCESS_TOKEN_HASH"), {
    api_name: "ACCESS_TOKEN_HASH",
    type: "varchar",
    max_length: 64,
    mandatory: true,
    unique: false,
    pii_ephi: true,
  });
  assert.equal(sessionColumns.has("TOKEN_HASH"), false);
  assert.equal(sessionColumns.has("ISSUE_KEY"), false);
  assert.equal(sessionColumns.get("LAST_OUTCOME").pii_ephi, true);
  assert.match(sessionTable.retention, /Do not delete or alter any session row/);
  assert.equal(
    schema.deployment_gates.some((gate) =>
      gate.includes("zero rows") && gate.includes("schema version 3")),
    true,
  );
  assert.equal(
    schema.deployment_gates.some((gate) =>
      gate.includes("any row exists") && gate.includes("distinct version-3 table") && gate.includes("preserve")),
    true,
  );
  assert.equal(
    schema.deployment_gates.some((gate) =>
      gate.includes("LAST_OUTCOME") && gate.includes("read back")),
    true,
  );
  assert.equal(
    schema.deployment_gates.some((gate) =>
      gate.includes("legacy Form 2 project live") && gate.includes("separate destructive action")),
    true,
  );
  assert.equal(JSON.stringify(schema).includes("RAW_PAYLOAD"), false);
});

test("the Catalyst and npm manifests describe one consistent Advanced IO target", () => {
  const catalyst = readJson(path.join(controllerRoot, "catalyst.json"));
  assert.deepEqual(catalyst, {
    functions: {
      source: "functions",
      targets: ["form2_controller"],
      ignore: ["test/**", ".env*"],
    },
  });

  const sourceRoot = path.join(controllerRoot, catalyst.functions.source);
  const targetRoot = path.join(sourceRoot, catalyst.functions.targets[0]);
  assert.equal(path.resolve(targetRoot), functionRoot);
  assert.equal(fs.statSync(sourceRoot).isDirectory(), true);
  assert.equal(fs.statSync(targetRoot).isDirectory(), true);

  const catalystConfigPath = path.join(targetRoot, "catalyst-config.json");
  const packagePath = path.join(targetRoot, "package.json");
  const packageLockPath = path.join(targetRoot, "package-lock.json");
  const catalystConfig = readJson(catalystConfigPath);
  const packageJson = readJson(packagePath);
  const packageLock = readJson(packageLockPath);

  assert.deepEqual(catalystConfig, {
    deployment: {
      name: "form2_controller",
      stack: "node24",
      type: "advancedio",
    },
    execution: { main: "index.js" },
  });
  assert.equal(catalystConfig.deployment.name, catalyst.functions.targets[0]);
  const expectedRuntimeSources = [
    "index.js",
    "lib/catalyst-adapter.js",
    "lib/catalyst-datastore-adapter.js",
    "lib/config.js",
    "lib/connection-boundary.js",
    "lib/crm-client.js",
    "lib/destinations.js",
    "lib/form-destination.js",
    "lib/form-contract.js",
    "lib/handler.js",
    "lib/http.js",
    "lib/operation-timeout.js",
    "lib/safe-log.js",
    "lib/security.js",
    "lib/session-store.js",
    "lib/snapshot.js",
    "lib/source-revision.js",
    "lib/verification-proof.js",
    "lib/workflow-store.js",
  ];
  const expectedCheckScript = expectedRuntimeSources
    .map((sourceFile) => `node --check ${sourceFile}`)
    .join(" && ");
  assert.deepEqual(packageJson, {
    name: "sylvara-form2-controller",
    version: "0.1.0",
    private: true,
    description: "Development-blocked Zoho Forms Form 2 prefill and submission controller for Zoho Catalyst.",
    main: "index.js",
    type: "commonjs",
    engines: { node: "24.x" },
    scripts: {
      check: expectedCheckScript,
      test: "node --test test/*.test.js",
      ci: "npm run check && npm test",
    },
    dependencies: { "zcatalyst-sdk-node": "3.4.0" },
  });
  assert.equal(packageJson.main, catalystConfig.execution.main);

  assert.deepEqual(sorted(Object.keys(packageLock)), sorted([
    "name",
    "version",
    "lockfileVersion",
    "requires",
    "packages",
  ]));
  assert.equal(packageLock.lockfileVersion, 3);
  assert.equal(packageLock.requires, true);
  assert.equal(packageLock.name, packageJson.name);
  assert.equal(packageLock.version, packageJson.version);
  assert.deepEqual(packageLock.packages[""], {
    name: packageJson.name,
    version: packageJson.version,
    dependencies: packageJson.dependencies,
    engines: packageJson.engines,
  });
  assert.deepEqual(sorted(Object.keys(packageLock.packages)), sorted([
    "",
    "node_modules/agent-base",
    "node_modules/debug",
    "node_modules/https-proxy-agent",
    "node_modules/ms",
    "node_modules/zcatalyst-sdk-node",
  ]));
  for (const [packagePath, metadata] of Object.entries(packageLock.packages)) {
    assert.notEqual(metadata.hasInstallScript, true, `${packagePath} has an install script`);
    assert.equal(metadata.link, undefined, `${packagePath} is a linked dependency`);
    if (packagePath !== "") {
      assert.match(metadata.resolved, /^https:\/\/registry\.npmjs\.org\//);
      assert.match(metadata.integrity, /^sha512-[A-Za-z0-9+/]+=*$/);
    }
  }
  assert.equal(packageLock.packages["node_modules/zcatalyst-sdk-node"].version, "3.4.0");
  assert.match(
    packageLock.packages["node_modules/zcatalyst-sdk-node"].resolved,
    /\/zcatalyst-sdk-node-3\.4\.0\.tgz$/,
  );
  assert.match(
    packageLock.packages["node_modules/zcatalyst-sdk-node"].integrity,
    /^sha512-[A-Za-z0-9+/]+=*$/,
  );

  for (const referencedFile of [
    catalystConfig.execution.main,
    "catalyst-config.json",
    "package.json",
    "package-lock.json",
  ]) {
    assert.equal(
      fs.statSync(path.join(targetRoot, referencedFile)).isFile(),
      true,
      `${referencedFile} is missing`,
    );
  }

  const runtimeSources = walkFiles(targetRoot)
    .filter((relativePath) => relativePath === "index.js" || /^lib\/.*\.js$/.test(relativePath));
  assert.deepEqual(sorted(runtimeSources), sorted(expectedRuntimeSources));
  for (const sourceFile of expectedRuntimeSources) {
    assert.equal(fs.statSync(path.join(targetRoot, sourceFile)).isFile(), true);
  }
});

test("the intended function archive excludes tests and environment files", () => {
  const catalyst = readJson(path.join(controllerRoot, "catalyst.json"));
  const targetRoot = path.join(
    controllerRoot,
    catalyst.functions.source,
    catalyst.functions.targets[0],
  );
  const allFiles = walkFiles(targetRoot);
  const archiveFiles = allFiles.filter(
    (relativePath) => !matchesManifestIgnore(relativePath, catalyst.functions.ignore),
  );

  assert.ok(allFiles.includes("test/registry.test.js"));
  assert.ok(allFiles.includes(".env.example"));
  assert.equal(archiveFiles.some((relativePath) => relativePath.startsWith("test/")), false);
  assert.equal(
    archiveFiles.some((relativePath) => path.posix.basename(relativePath).startsWith(".env")),
    false,
  );

  for (const requiredFile of [
    "index.js",
    "catalyst-config.json",
    "package.json",
    "package-lock.json",
  ]) {
    assert.ok(archiveFiles.includes(requiredFile), `${requiredFile} is absent from the archive`);
  }
  const runtimeLibraries = allFiles.filter((relativePath) => /^lib\/.*\.js$/.test(relativePath));
  assert.ok(runtimeLibraries.length > 0);
  for (const runtimeLibrary of runtimeLibraries) {
    assert.ok(archiveFiles.includes(runtimeLibrary), `${runtimeLibrary} is absent from the archive`);
  }
});

test("the repository pipeline keeps approval but blocks Development deployment", () => {
  const pipelinePath = path.join(repositoryRoot, "catalyst-pipelines.yaml");
  const scriptPath = path.join(controllerRoot, "scripts/deploy-development.sh");
  const revisionModulePath = path.join(functionRoot, "lib/source-revision.js");
  const formDestinationModulePath = path.join(functionRoot, "lib/form-destination.js");
  const pipeline = fs.readFileSync(pipelinePath, "utf8");
  const script = fs.readFileSync(scriptPath, "utf8");
  const revisionModule = fs.readFileSync(revisionModulePath, "utf8");
  const formDestinationModule = fs.readFileSync(formDestinationModulePath, "utf8");

  assert.match(pipeline, /^version: 1$/m);
  assert.match(pipeline, /^  approve:\n    type:\n      type-name: approval$/m);
  const approvalStageIndex = pipeline.indexOf("- name: approval");
  const developmentStageIndex = pipeline.indexOf("- name: development");
  assert.notEqual(approvalStageIndex, -1, "the approval stage is missing");
  assert.notEqual(developmentStageIndex, -1, "the Development stage is missing");
  assert.ok(
    approvalStageIndex < developmentStageIndex,
    "the approval stage must precede the deployment stage",
  );
  assert.match(pipeline, /<< env\.DEPLOY_APPROVER_EMAIL >>/);
  const deploymentJob = pipeline
    .split(/^  deploy_form2_development:\n/m)[1]
    ?.split(/^stages:\n/m)[0];
  assert.ok(deploymentJob, "the Development deployment job is missing");
  assert.equal(
    deploymentJob.trimEnd(),
    `    steps:
      - |
        set +x
        printf '%s\\n' 'BLOCKED: Form 2 Development deployment requires a verified native secret binding.' >&2
        exit 1`,
  );
  assert.doesNotMatch(deploymentJob, /<<\s*env\./);
  for (const forbiddenVariableName of [
    "PROJECT_ID",
    "CATALYST_ORG",
    "CATALYST_TOKEN",
    "APPROVED_SOURCE_REVISION",
    "APPROVED_FORM2_DESTINATION_SHA256",
  ]) {
    assert.doesNotMatch(pipeline, new RegExp(`<< env\\.${forbiddenVariableName} >>`));
  }
  assert.match(
    deploymentJob,
    /printf '%s\\n' 'BLOCKED: Form 2 Development deployment requires a verified native secret binding\.' >&2/,
  );
  assert.match(deploymentJob, /^      - \|\n        set \+x\n/m);
  assert.match(deploymentJob, /^        exit 1$/m);
  assert.doesNotMatch(deploymentJob, /deploy-development\.sh|\bcatalyst\s+deploy\b/);
  assert.doesNotMatch(pipeline, /BASH_ENV=|ENV=|SHELLOPTS=|PS4=/);

  assert.notEqual(fs.statSync(scriptPath).mode & 0o111, 0, "deployment script is not executable");
  assert.match(script, /^#!\/usr\/bin\/env bash\nset \+x\nset -euo pipefail$/m);
  assert.match(script, /readonly NODE_VERSION="24\.19\.0"/);
  assert.match(script, /readonly CATALYST_CLI_VERSION="1\.26\.1"/);
  assert.match(
    script,
    /readonly NODE_SHA256="14b342e71204f811bde6153be8e04b62aef63c236fef92b55f9c83154b409647"/,
  );
  assert.match(script, /actual_revision.*run_isolated_git .* rev-parse --verify HEAD/);
  assert.match(script, /actual_revision" == "\$APPROVED_SOURCE_REVISION/);
  assert.match(script, /status --porcelain=v1 --untracked-files=all/);
  assert.equal(revisionModule, `"use strict";

// The Development deploy script replaces this sentinel only after proving that
// Git HEAD equals APPROVED_SOURCE_REVISION. An unstamped or manually packaged
// function therefore fails configuration before it can access CRM or Data Store.
const ARTIFACT_SOURCE_REVISION = "__SYLVARA_UNSTAMPED_SOURCE_REVISION__";

module.exports = { ARTIFACT_SOURCE_REVISION };
`);
  assert.equal(formDestinationModule, `"use strict";

// A CODEOWNERS-reviewed source change must replace this sentinel with the
// SHA-256 of the one approved normalized Zoho Forms URL. The deploy script may
// verify this value but must never derive or stamp it from runtime input.
const ARTIFACT_FORM_DESTINATION_SHA256 =
  "__SYLVARA_UNSTAMPED_FORM_DESTINATION_SHA256__";

module.exports = { ARTIFACT_FORM_DESTINATION_SHA256 };
`);
  assert.match(script, /run_isolated_git .* archive --format=tar "\$actual_revision"/);
  assert.match(script, /catalyst-pipelines\.yaml \|/);
  assert.match(script, /approved pipeline export is unavailable/);
  assert.match(script, /"ls-tree", "-r", "-z", revision/);
  assert.match(script, /mode not in \{"100644", "100755"\}/);
  assert.match(script, /approved Git export contains an unsupported mode or object type/);
  assert.match(script, /approved Git export content differs from its Git blob/);
  assert.match(script, /approved Git export paths differ from the reviewed Git tree/);
  assert.match(script, /test-export/);
  assert.match(script, /deploy-export/);
  assert.match(script, /reference-export/);
  assert.match(script, /source revision module is not the exact reviewed sentinel template/);
  assert.match(script, /replacement = f'const ARTIFACT_SOURCE_REVISION = "\{revision\}";'/);
  assert.match(script, /artifact_revision" == "\$actual_revision/);
  assert.match(script, /APPROVED_FORM2_DESTINATION_SHA256.*\^\[a-f0-9\]\{64\}\$/);
  assert.match(script, /reviewed source form destination is not approved/);
  assert.match(script, /read_approved_form_destination "\$form_destination_path"/);
  assert.doesNotMatch(script, /stamp_form_destination/);
  assert.match(
    script,
    /artifact_form_destination" == "\$APPROVED_FORM2_DESTINATION_SHA256/,
  );
  assert.doesNotMatch(script, /require\(process\.argv\[1\]\)\.ARTIFACT_SOURCE_REVISION/);
  assert.doesNotMatch(script, /--exclude=node_modules/);
  assert.match(script, /function_dependency_subtree="functions\/form2_controller\/node_modules"/);
  assert.match(script, /reference_source_manifest/);
  assert.match(script, /deploy_source_manifest/);
  assert.match(script, /deployable controller differs from the approved Git export/);
  assert.doesNotMatch(script, /source-revision\.js\.original|revision_backup_path/);
  assert.match(script, /tools\/safety\/pre-commit-safety-check\.py/);
  assert.match(script, /run_isolated_npm/);
  assert.match(script, /env -i/);
  assert.match(script, /npm_config_globalconfig/);
  assert.equal(
    (script.match(/ci --omit=dev --ignore-scripts --no-audit --no-fund/g) ?? []).length,
    2,
  );
  assert.match(script, /--ignore-scripts run ci/);
  assert.match(script, /manifest_tree/);
  assert.match(script, /tested and deployable dependency trees differ/);
  assert.match(script, /artifact symlink escapes its tree/);
  assert.match(script, /artifact path has special permission bits/);
  assert.match(script, /artifact directory has special permission bits/);
  assert.match(script, /artifact regular file is group- or world-writable/);
  assert.match(script, /artifact contains an unsupported file type/);
  assert.match(script, /rm -rf -- "\$deploy_function_root\/test"/);
  assert.doesNotMatch(script, /find "\$deploy_function_root" -maxdepth 1 -name '\.env\*'/);
  assert.match(script, /unreviewed Catalyst project-state file entered the export/);
  assert.match(script, /deployment cleanup failed; deployment may have completed/);
  assert.match(
    script,
    /export -n PROJECT_ID CATALYST_ORG CATALYST_TOKEN APPROVED_SOURCE_REVISION/,
  );
  assert.match(script, /GIT_\*\|npm_config_\*\|NPM_CONFIG_\*/);
  const unexportIndex = script.indexOf(
    "export -n PROJECT_ID CATALYST_ORG CATALYST_TOKEN APPROVED_SOURCE_REVISION",
  );
  assert.notEqual(unexportIndex, -1);
  assert.ok(unexportIndex < script.indexOf('git_directory="$(dirname'));
  assert.ok(unexportIndex < script.indexOf('runner_architecture="$(uname'));
  assert.match(script, /GIT_NO_REPLACE_OBJECTS=1/);
  assert.match(script, /"GIT_NO_REPLACE_OBJECTS": "1"/);
  assert.doesNotMatch(script, /npm install[^\n]*zcatalyst-cli|zcatalyst-cli@/);
  assert.equal((script.match(/"\$catalyst_path" deploy/g) ?? []).length, 1);
  assert.match(
    script,
    /deployment may have completed; independently read back the Development function and deployment before any retry/,
  );
  assert.match(script, /trap deployment_interrupted HUP INT TERM/);
  assert.match(script, /cd -- "\$deploy_project_root"/);
  assert.match(script, /--only functions:form2_controller/);
  assert.match(script, /--ignore-scripts/);
  assert.match(script, /--project "\$PROJECT_ID"/);
  assert.match(script, /--org "\$CATALYST_ORG"/);
  assert.match(script, /--token "\$CATALYST_TOKEN"/);
  assert.match(script, /--dc us/);
  assert.doesNotMatch(script, /set -x|--verbose/);
});
